project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!archive/"
    - "!day1/"
    - "!day2/"
    - "!GIS/"
    - "!modules/ODEs-optim.qmd"

website:
  title: "SISMID R for ID Materials (2026)"
  sidebar:
    style: docked
    search: true
    pinned: true
    tools:
      - icon: github
        href: https://github.com/wzbillings/SISMID-2026
    contents:
      - text: "Welcome!"
        href: index.qmd
      - text: "Course Schedule"
        href: schedule.qmd
      - text: "Course Resources"
        href: references.qmd
      - text: "Course Data README"
        href: data-readme.qmd
      - section: "Day 1 core"
        contents:
          - text: "Module 0: Welcome"
            href: modules/Module00-Welcome.qmd
            target: _blank
          - text: "Module 1: Quarto"
            href: modules/Module01-Quarto.qmd
            target: _blank
          - text: "Module 2: Stats in R"
            href: modules/Module02-StatReview.qmd
            target: _blank
          - text: "Module 3: Iteration"
            href: modules/Module03-Iteration.qmd
            target: _blank
          - text: "Module 4: Writing functions"
            href: modules/Module04-Functions.qmd
            target: _blank
          - text: "Data science walkthrough 1: conditionals"
            href: modules/Walkthrough1.qmd
            target: _blank
      - section: "Day 2 core"
        contents:
          - text: "Module 5: Functional programming"
            href: modules/Module05-FunctionalProgramming.qmd
            target: _blank
          - text: "Useful R packages"
            href: modules/UsefulPackages.qmd
            target: _blank
          - text: "Module 6: S3 and formulas"
            href: modules/Module06-S3-lm-formulas.qmd
            target: _blank
          - text: "Data science walkthrough 2: iteration"
            href: modules/Walkthrough2.qmd
            target: _blank
      - section: "Day 3 core"
        contents:
          - text: "ODEs with deSolve"
            href: modules/ODEs.qmd
            target: _blank
          - text: "Disease mapping and GIS"
            href: modules/DiseaseMapping.qmd
            target: _blank
      - section: "Exercises"
        contents:
          - text: "QCRC report checklist/rubric"
            href: exercises/qcrc-report-checklist-rubric.qmd
            target: _blank
          - text: "QCRC starter template"
            href: exercises/qcrc-mini-manuscript-starter.qmd
            target: _blank
          - text: "Exercise 1"
            href: exercises/Exercise1.qmd
            target: _blank
          - text: "Exercise 2"
            href: exercises/Exercise2.qmd
            target: _blank
      - section: "Optional / advanced / take-home"
        contents:
          - text: "Bootstrapping"
            href: modules/bootstrapping.qmd
            target: _blank
          - text: "Arrow"
            href: modules/Arrow.qmd
            target: _blank
          - text: "Power simulation"
            href: modules/power-sim.qmd
            target: _blank
          - text: "Likelihoods with optim"
            href: modules/optim-likelihood.qmd
            target: _blank
          - text: "Fitting ODE models"
            href: modules/ODE-parameter-fitting.qmd
            target: _blank
  repo-url: https://github.com/wzbillings/SISMID-2026
  reader-mode: true

# Default for table of contents
toc: true
toc-title: Page Items
toc-location: right

# Default knitr options
execute:
  echo: true
  message: true
  warning: true
  freeze: auto

engine: knitr

# Default author
author:
  - name: "Alex Edwards"
    url: https://sph.emory.edu/profile/faculty/alex-edwards
  - name: "Zane Billings"
    url: https://wzbillings.com/

# Default fields for citation
license: "CC BY-NC"

format:
  html:
    theme:
      light: [cosmo, format/_fonts.scss, format/_light.scss, format/_callouts.scss]
      dark: [cosmo, format/_fonts.scss, format/_dark.scss, format/_callouts.scss]
    grid:
      sidebar-width: 270px
      body-width: 1000px
      margin-width: 200px
      gutter-width: 1rem
    code-copy: true
    code-fold: show
    code-overflow: wrap
    code-link: true
    code-tools: true
    code-line-numbers: true

# Extension Lua filters
filters:
  - line-highlight
